openapi: 3.0.0

info:
  title: "Trail Service API"
  version: "1.0.0"
  description: "A simple API to manage trails"
  contact:
    name: "Henry Reid"
    email: "henryreid05@gmail.com"
    url: "https://henryreid.com"

servers:
  - url: "/api"


components:
  schemas:
    Trail:
      type: object
      properties: 
        trail_id:
          type: integer
        route_id:
          type: integer
        owner_id:
          type: integer
        name:
          type: string
        difficulty:
          type: string
        location:
          type: string
        length:
          type: number
        elevation_gain:
          type: number
        description:
          type: string

paths:

