openapi: 3.0.0
info:
  title: Trail Service API
  description: API for managing trail services
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /trails:
    get:
      summary: Get all trails
      responses:
        '200':
          description: A list of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trail'
    post:
      summary: Create a new trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        '201':
          description: Trail created
components:
  schemas:
    Trail:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
        length:
          type: number
          format: float
        difficulty:
          type: string
          enum:
            - easy
            - moderate
            - hard
      required:
        - name
        - location
        - length
        - difficulty