openapi: 3.0.0

info:
  title: "Trail Service API"
  version: "1.0.0"
  description: "A simple API to manage trails and owners"
  contact:
    name: "Henry Reid"
    email: "henryreid05@gmail.com"
    url: "https://henryreid.com"

servers:
  - url: "/api"

components:
  schemas:
    Trail:
      type: object
      properties:
        name:
          type: string
          description: "Name of the trail"
        difficulty:
          type: string
          description: "Difficulty level of the trail (e.g., Easy, Medium, Hard)"
        location:
          type: string
          description: "Location of the trail"
        length:
          type: number
          format: float
          description: "Length of the trail in miles or kilometers"
        elevation_gain:
          type: number
          format: float
          description: "Elevation gain of the trail in feet or meters"
        description:
          type: string
          description: "A detailed description of the trail"
        owner_id:
          type: integer
          description: "ID of the trail's owner"
        route_id:
          type: integer
          description: "ID of the trail's route type"
        trail_points:
          type: array
          items:
            type: object
            properties:
              location_point_id:
                type: integer
              sequence_number:
                type: integer
          description: "List of location points for the trail"
        trail_features:
          type: array
          items:
            type: object
            properties:
              feature_id:
                type: integer
          description: "List of features associated with the trail"

    TrailPoints:
      type: object
      properties:
        location_point_id:
          type: integer
          description: "ID of the location point"
        sequence_number:
          type: integer
          description: "The order of the location point in the trail"
      required:
        - location_point_id
        - sequence_number

    TrailFeatures:
      type: object
      properties:
        feature_id:
          type: integer
          description: "ID of the feature"
      required:
        - feature_id
  
  parameters:
    trail_id:
      name: "trail_id"
      in: "path"
      required: true
      schema:
        type: "integer"
      description: "ID of the trail to return"
    email:
      name: "email"
      in: "header"
      required: true
      description: "Email of the user"
      schema: 
        type: "string"
    password:
      name: "password"
      in: "header"
      required: true
      description: "Password of the user"
      schema: 
        type: "string"

paths:
  "/trails":
    get:
      tags: ["trails"]
      operationId: "endpoints.trails.read_all"
      summary: "Get all trails"
      description: "Returns a list of all trails"
      responses:
        "200":
          description: "A list of trails"
    post:
      tags: ["trails"]
      operationId: "endpoints.trails.create"
      summary: "Create a new trail"
      description: "Creates a new trail, optionally with trail points and features"
      parameters:
        - schema:
          $ref: "#/components/parameters/email"
        - schema:
          $ref: "#/components/parameters/password"
      requestBody:
        description: "Trail object to be created"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail created"

  "/trails/{trail_id}":
    get:
      tags: ["trails"]
      operationId: "endpoints.trails.read_one"
      summary: "Get a trail by ID"
      description: "Returns a trail by ID"
      parameters:
        - schema:
          $ref: "#/components/parameters/trail_id"
      responses:
        "200":
          description: "A trail"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "404":
          description: "Not Found - Trail with the given ID doesn't exist"
    put:
      tags: ["trails"]
      operationId: "endpoints.trails.update"
      summary: "Update a trail"
      description: "Updates a trail by ID"
      parameters:
        - schema:
          $ref: "#/components/parameters/trail_id"
        - schema:
          $ref: "#/components/parameters/email"
        - schema:
          $ref: "#/components/parameters/password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "200":
          description: "Trail updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    delete:
      tags: ["trails"]
      operationId: "endpoints.trails.delete"
      summary: "Delete a trail"
      description: "Deletes a trail by ID."
      parameters:
        - schema:
          $ref: "#/components/parameters/trail_id"
        - schema:
          $ref: "#/components/parameters/email"
        - schema:
          $ref: "#/components/parameters/password"
      responses:
        "204":
          description: "Trail deleted"
        "404":
          description: "Not Found - Trail with the given ID doesn't exist"

