openapi: 3.0.0

info:
  title: "Trail Service API"
  version: "1.0.0"
  description: "A simple API to manage trails"
servers:
  - url: "/api"

components:
  schemas:
    Trail:
      type: "object"
      properties:
        trail_id:
          type: "integer"
        name:
          type: "string"
        difficulty:
          type: "string"
        location:
          type: "string"
        length:
          type: "number"
        elevation_gain:
          type: "number"
        owner_id:
          type: "integer"
        route_id:
          type: "integer"

paths:
  /trails:
    get:
      summary: "Get all trails"
      operationId: "trails.read_all"
      responses:
        '200':
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      summary: "Create a new trail"
      operationId: "trails.create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        '201':
          description: "Trail created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
  /trails/{trail_id}:
    get:
      summary: "Get a trail by ID"
      operationId: "trails.read_one"
      parameters:
        - name: "trail_id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "A trail"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    put:
      summary: "Update a trail by ID"
      operationId: "trails.update"
      parameters:
        - name: "trail_id"
          in: "path"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        '200':
          description: "Trail updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    delete:
      summary: "Delete a trail by ID"
      operationId: "trails.delete"
      parameters:
        - name: "trail_id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        '204':
          description: "Trail deleted"
